create or replace view AIMS.INTO_APPLIANCE_VIEW as
select a.ID,a.ARCHIVES_TIME,a.CATEGORY_ID,a.CODE,CREATE_BY,a.CREATE_TIME,a.FIRST_INSPECT_BY,a.FIRST_INSPECT_DATE,a.LAST_EXP_TIME,
       a.MANUFACTURER_ID,a.NEXT_EXP_TIME,a.PRODUCE_DATE,a.SERIAL_NUM,a.SPEC_ID,a.STATION_ID,a.STATUS,a.PURCHASE_ORDER,a.PAIR_COUNT,a.CHECK_DATE,
       a.IS_NORMAL,a.INSTALLATION,a.DISMANTLE,a.IS_PRINT,a.RECIPIENTS,a.LAST_UPDATE_TIME,a.NEW_STATUS,
       b."NAME" STATION_NAME,b.GROUP_ID,b.EXP_CENTER_ID,
       c.NAME MANUFACTURER_NAME,
       d."SPEC" SPEC_NAME,d.EXP_PARAMS EXP_PARAMS,d.VOLTAGE,
       e."NAME" CATEGORY_NAME,e."CATEGORY_PATH" CATEGORY_PATH,e.EXP_PERIOD EXP_PERIOD,e.IS_PERIOD IS_PERIOD,e.SHELF_LIFE SHELF_LIFE,e.EXPPARAM_TYPE EXPPARAM_TYPE,
       f.path org_path,f.NAME org_name,f.BMXZNAME org_BMXZNAME,f.com_bmjc org_com_bmjc,f.PARENTID
from AIMS.INTO_APPLIANCE a
         left join AIMS.INTO_STATION b on a.STATION_ID=b."ID"
         left join AIMS.INTO_MANUFACTURER c on a.MANUFACTURER_ID=c.ID
         left join AIMS.INTO_APPLIANCE_SPEC d on a.SPEC_ID=d.ID
         left join AIMS.INTO_APPLIANCE_CATEGORY e on a.CATEGORY_ID=e.id
         left join AIMS.COM_BASEORGNAIZE f on b.GROUP_ID=f.OBJ_ID
/

create or replace view AIMS.INTO_BUSINESS_OUT_IN_VIEW as
select a.id,a.APPLIANCE_ID,to_char(a.OUT_IN_TIME,'YYYY-MM-DD HH:MM:SS') OUT_IN_TIME,a.IS_CHECK,a.OPRATE_TYPE,a.ORDER_NUMBER,a.OUT_IN_TYPE,a.USER_ID,a.EXP_ORDER,a.PURCHASE_ORDER,
       a.USER_ID_NAME,
       g.ARCHIVES_TIME,g.CATEGORY_ID,g.CODE,
       g.MANUFACTURER_ID,g.PRODUCE_DATE,g.SERIAL_NUM,g.SPEC_ID,g.STATION_ID,g.STATUS,g.PAIR_COUNT,g.CHECK_DATE,
       g.RECIPIENTS,
       b."NAME" STATION_NAME,b.GROUP_ID,
       d."SPEC" SPEC_NAME,d.VOLTAGE,
       e."NAME" CATEGORY_NAME,
       f.path org_path,f.NAME org_name,f.BMXZNAME org_BMXZNAME,f.com_bmjc org_com_bmjc
from AIMS.INTO_BUSINESS_OUT_IN a
         LEFT JOIN AIMS.INTO_APPLIANCE g on a.APPLIANCE_ID=g."ID"
         left join AIMS.INTO_STATION b on g.STATION_ID=b."ID"
         left join AIMS.INTO_APPLIANCE_SPEC d on g.SPEC_ID=d.ID
         left join AIMS.INTO_APPLIANCE_CATEGORY e on g.CATEGORY_ID=e.id
         left join AIMS.COM_BASEORGNAIZE f on b.GROUP_ID=f.OBJ_ID
/

create or replace view AIMS.INTO_EXPCENTER_TO_COMPANY_VIEW as
select a.ID,a.EXP_CENTER_ID,a.COMPANY_ID,
       b.path org_path,b.NAME org_name,
       c.EXP_CENTER_NAME EXP_CENTER_NAME,c.IS_ENABLE IS_ENABLE,
       d.PATH exp_org_path
from AIMS.INTO_EXP_CENTER_COMPANY a
         LEFT JOIN AIMS.COM_BASEORGNAIZE b on a.COMPANY_ID=b.OBJ_ID
         LEFT JOIN AIMS.INTO_EXP_COMPANY_REL c on a.EXP_CENTER_ID=c."ID"
         LEFT JOIN AIMS.COM_BASEORGNAIZE d on c.EXP_GROUP_ID=d.OBJ_ID
/


create or replace view AIMS.INTO_EXPCENTER_VIEW as
select a."ID",a."EXP_CENTER_NAME",a."COMPANY_NAME",a."IS_ENABLE",a."CREATE_TIME",a."AREA",a."ADDRESS",a."INFORMATION",
       a."MAXIMUM_ALLOWANCE",a."MINIMUM_ALLOWANCE",a.IS_DELETE,
       a."STATIONNUM",a."UNQUALIFIED",a."SEAL",a."EXP_GROUP_ID",

       b.path org_path,b.NAME org_name,b.BMXZNAME org_BMXZNAME,b.com_bmjc org_com_bmjc

from AIMS.INTO_EXP_COMPANY_REL a
         LEFT JOIN AIMS.COM_BASEORGNAIZE b on a.EXP_GROUP_ID=b.OBJ_ID
/

create or replace view AIMS.INTO_EXPERIMENT_APPLIANCE_VIEW as
select a.id,a.APPLIANCE_ID,a.ALLOCATE_ORDER,a.EXP_ORDER,a.REASON,a.RESULT,a.IS_SUBJOIN,a.RESULT_JSON,a.IS_PRINT,a.FINISH_DATE,
       a.IS_ALLOCATION,a.IS_GRANT,a.IS_DISCERN,a.EXP_STATUS,a.LAST_UPDATE_TIME,a.IS_SCRAP,a.SUBJOIN_APPLIANCE_ID,
       g.ARCHIVES_TIME,g.CATEGORY_ID,g.CODE,g.FIRST_INSPECT_DATE,g.LAST_EXP_TIME,g.NEXT_EXP_TIME,g.STATUS,g.NEW_STATUS,
       g.MANUFACTURER_ID,g.PRODUCE_DATE,g.SERIAL_NUM,g.SPEC_ID,g.STATION_ID,g.PURCHASE_ORDER,g.PAIR_COUNT,g.CHECK_DATE,
       g.RECIPIENTS,
       c.EXP_CENTER_ID,
       b."NAME" STATION_NAME,d.EXP_PARAMS EXP_PARAMS,
       d."SPEC" SPEC_NAME,d.VOLTAGE,
       e."NAME" CATEGORY_NAME,e.PHENOMENON PHENOMENON,e.EXPPARAM_TYPE EXPPARAM_TYPE,e.EXP_PERIOD EXP_PERIOD,e.IS_PERIOD IS_PERIOD,e.SHELF_LIFE SHELF_LIFE
from AIMS.INTO_EXPERIMENT a
         left join AIMS.INTO_EXPERIMENT_MAIN c on c.EXP_ORDER = a.EXP_ORDER
         LEFT JOIN AIMS.INTO_APPLIANCE g on a.APPLIANCE_ID=g."ID"
         left join AIMS.INTO_STATION b on g.STATION_ID=b."ID"
         left join AIMS.INTO_APPLIANCE_SPEC d on g.SPEC_ID=d.ID
         left join AIMS.INTO_APPLIANCE_CATEGORY e on g.CATEGORY_ID=e.id
/

create or replace view AIMS.INTO_EXPERIMENT_MAIN_VIEW as
select a.id,a.APPLY_BY,a.APPLY_DATE,a.EXP_CENTER_ID,a.EXP_ORDER,a.EXP_TYPE,a.FINISH_DATE,a.CALIBRATION_BY,a.GROUP_ID,a.HUMIDITY,a.TEMPERATURE,
       a.AGREE_BY,a.EXP_BY,a.CREATE_TIME,a.APPLIANCE_NUM,a.GOOD_NUM,a.BAD_NUM,a.SUBJOIN_NUM,a.EXP_STATUS,a.SCRAP_STATUS,a.SCRAP_NUM,a.SCRAP_TRUE_NUM,
       a.APPLY_BY_NAME,a.CALIBRATION_BY_NAME,a.AGREE_BY_NAME,a.EXP_BY_NAME,
       c.EXP_CENTER_NAME EXP_CENTER_NAME,c.SEAL,
       f.path org_path,f.NAME org_name,
       g.obj_id exp_org_id,g.NAME exp_org_name,g.PATH exp_org_path,g.BMXZNAME org_BMXZNAME,g.com_bmjc org_com_bmjc
from AIMS.INTO_EXPERIMENT_MAIN a
         left join AIMS.INTO_EXP_COMPANY_REL c on a.EXP_CENTER_ID=c."ID"
         left join AIMS.COM_BASEORGNAIZE f on a.GROUP_ID=f.OBJ_ID
         left join AIMS.COM_BASEORGNAIZE g on c.EXP_GROUP_ID=g.OBJ_ID
/

create or replace view AIMS.INTO_INSPECTION_APPLIANCE_VIEW as
select a.id,a.APPLIANCE_ID,a.INSPECT_BY,a.INSPECT_DATE,a.INSPECT_NUM,a.REASON,a.STATUS,a.APPLY_BY,a.APPLY_DATE,
       g.ARCHIVES_TIME,g.CATEGORY_ID,g.CODE,
       g.MANUFACTURER_ID,g.PRODUCE_DATE,g.SERIAL_NUM,g.SPEC_ID,g.STATION_ID,g.PURCHASE_ORDER,g.PAIR_COUNT,g.CHECK_DATE,
       g.RECIPIENTS,g.STATUS APPLIANCE_STATUS,g.NEW_STATUS as APPLIANCE_NEW_STATUS,
       b."NAME" STATION_NAME,
       d."SPEC" SPEC_NAME,d.VOLTAGE,
       e."NAME" CATEGORY_NAME,e.DESC_STAND,
       f.NAME ORG_NAME , f.path ORG_PATH,f.BMXZNAME org_BMXZNAME,f.com_bmjc org_com_bmjc
from AIMS.INTO_INSPECTION a
         LEFT JOIN AIMS.INTO_APPLIANCE g on a.APPLIANCE_ID=g."ID"
         left join AIMS.INTO_STATION b on g.STATION_ID=b."ID"
         left join AIMS.INTO_APPLIANCE_SPEC d on g.SPEC_ID=d.ID
         left join AIMS.INTO_APPLIANCE_CATEGORY e on g.CATEGORY_ID=e.id
         left join AIMS.COM_BASEORGNAIZE f on f.OBJ_ID=b.GROUP_ID
/

create or replace view AIMS.INTO_INSPECTION_MAIN_VIEW as
select a.id,a.APPLY_BY,a.APPLY_DATE,a.INSPECT_BY,a.INSPECT_DATE,a.INSPECT_NUM, a.INSPECT_STATUS,a.STATION_ID,a.APPLIANCE_NUM,a.GOOD_NUM,a.BAD_NUM,a.EXP_ORDER,
       a.APPLY_BY_NAME,a.INSPECT_BY_NAME,
       b."NAME" STATION_NAME,b.GROUP_ID,
       f.path org_path,f.NAME org_name,f.BMXZNAME org_BMXZNAME,f.com_bmjc org_com_bmjc
from AIMS.INTO_INSPECTION_MAIN a
         left join AIMS.INTO_STATION b on a.STATION_ID=b."ID"
         left join AIMS.COM_BASEORGNAIZE f on b.GROUP_ID=f.OBJ_ID
/

create or replace view AIMS.INTO_QUALITY_FEEDBACK_VIEW as
select a.id,a.APPLIANCE_ID,a.DESCRIBE,a.FEEDBACK_BY,a.FEEDBACK_TIME,a.REASON,a.URL,
       a.FEEDBACK_BY_NAME,
       g.ARCHIVES_TIME,g.CATEGORY_ID,g.CODE,
       g.MANUFACTURER_ID,g.PRODUCE_DATE,g.SERIAL_NUM,g.SPEC_ID,g.STATION_ID,g.STATUS,g.PURCHASE_ORDER,g.PAIR_COUNT,g.CHECK_DATE,
       g.RECIPIENTS,g.NEW_STATUS,
       b."NAME" STATION_NAME,b.GROUP_ID,
       c.NAME MANUFACTURER_NAME,
       d."SPEC" SPEC_NAME,d.VOLTAGE,
       e."NAME" CATEGORY_NAME,
       f.PATH org_path,f.NAME org_name,f.BMXZNAME org_BMXZNAME,f.com_bmjc org_com_bmjc
from AIMS.INTO_QUALITY_FEEDBACK a
         LEFT JOIN AIMS.INTO_APPLIANCE g on a.APPLIANCE_ID=g."ID"
         left join AIMS.INTO_STATION b on g.STATION_ID=b."ID"
         left join AIMS.INTO_MANUFACTURER c on g.MANUFACTURER_ID=c.ID
         left join AIMS.INTO_APPLIANCE_SPEC d on g.SPEC_ID=d.ID
         left join AIMS.INTO_APPLIANCE_CATEGORY e on g.CATEGORY_ID=e.id
         left join AIMS.COM_BASEORGNAIZE f on b.GROUP_ID=f.OBJ_ID
/

create or replace view AIMS.INTO_SCRAP_VIEW as
select a.id,a.APPLIANCE_ID,a.SCRAP_REASON,a.EXP_ORDER,a.SCRAP_TIME,a.SCRAP_TYPE,a.SCRAP_NUMBER,a.SCRAP_STATUS,
       g.ARCHIVES_TIME,g.CATEGORY_ID,g.CODE,
       g.MANUFACTURER_ID,g.PRODUCE_DATE,g.SERIAL_NUM,g.SPEC_ID,g.STATION_ID,g.STATUS,g.PURCHASE_ORDER,g.PAIR_COUNT,g.CHECK_DATE,
       g.RECIPIENTS,g.NEW_STATUS,
       b."NAME" STATION_NAME,b.GROUP_ID,
       c.NAME MANUFACTURER_NAME,
       d."SPEC" SPEC_NAME,d.VOLTAGE,
       e."NAME" CATEGORY_NAME,
       f.PATH org_path,f.NAME org_name
from AIMS.INTO_SCRAP a
         LEFT JOIN AIMS.INTO_APPLIANCE g on a.APPLIANCE_ID=g.ID
         left join AIMS.INTO_STATION b on g.STATION_ID=b."ID"
         left join AIMS.INTO_MANUFACTURER c on g.MANUFACTURER_ID=c.ID
         left join AIMS.INTO_APPLIANCE_SPEC d on g.SPEC_ID=d.ID
         left join AIMS.INTO_APPLIANCE_CATEGORY e on g.CATEGORY_ID=e.id
         left join AIMS.COM_BASEORGNAIZE f on b.GROUP_ID=f.OBJ_ID
/

create or replace view INTO_STATION_VIEW as
select a.ID ID,a.CREATE_TIME CREATE_TIME,a.NAME NAME,a.TYPE TYPE,a.STATUS STATUS,a.INSPECTION_TIME INSPECTION_TIME,a.LOCATION LOCATION,a.GROUP_ID,
       a.CODE CODE,a.PRINCIPAL PRINCIPAL,a.RANGE RANGE,a.LOCATION_BY LOCATION_BY,a.LOCATION_TIME LOCATION_TIME,a.EXP_CENTER_ID EXP_CENTER_ID,
       a.PRINCIPAL_NAME,a.LOCATION_BY_NAME,a.IMPORT_STATUS,a.IMPORT_ID,a.IMPORT_TIME,
       b.NAME org_name,b.PATH ORG_PATH ,b.BMXZNAME org_BMXZNAME,b.com_bmjc org_com_bmjc
from AIMS.INTO_STATION a
         LEFT JOIN AIMS.COM_BASEORGNAIZE b on a.GROUP_ID=b.OBJ_ID
/


create or replace view AIMS.INTO_COLLECT_NUMBER_MAIN_VIEW as
select a.ID,a.COLLECT_NUMBER,a.COLLECT_STATUS ,a.STATION_ID,a.APPLY_BY,a.APPLY_TIME,a.ORDER_TYPE,a.WORK_TICKET,
       a.BACK_BY,a.BACK_TIME,a.CREATE_TIME,a.APPLIANCE_NUM,
       a.APPLY_BY_NAME,a.BACK_BY_NAME,
       b.NAME as STATION_NAME,b.GROUP_ID,
       f.path org_path,f.NAME org_name,f.BMXZNAME org_BMXZNAME,f.com_bmjc org_com_bmjc
from AIMS.INTO_COLLECT_NUMBER_MAIN  a
         LEFT JOIN AIMS.INTO_STATION b on a.STATION_ID=b.ID
         left join AIMS.COM_BASEORGNAIZE f on b.GROUP_ID=f.OBJ_ID
/

create or replace view INTO_COLLECT_TO_APPLIANCE_VIEW as
select a.ID,a.COLLECT_NUMBER,a.APPLIANCE_ID ,a.COLLECT_STATUS,a.BACK_TIME,a.CREATE_TIME,a.COLLECT_TIME,a.LAST_UPDATE_TIME,
       a.WORK_TICKET,b.STATION_ID,
       c.NAME as STATION_NAME,
       d.ARCHIVES_TIME,d.CATEGORY_ID,d.CODE,
       d.MANUFACTURER_ID,d.PRODUCE_DATE,d.SERIAL_NUM,d.SPEC_ID,d.PURCHASE_ORDER,d.PAIR_COUNT,d.CHECK_DATE,
       d.RECIPIENTS,d.STATUS as APPLIANCE_STATUS,d.NEW_STATUS as APPLIANCE_NEW_STATUS,
       e.NAME CATEGORY_NAME,
       f.SPEC SPEC_NAME,f.VOLTAGE
from AIMS.INTO_COLLECT_TO_APPLIANCE  a
         LEFT JOIN AIMS.INTO_COLLECT_NUMBER_MAIN b on a.COLLECT_NUMBER=b.COLLECT_NUMBER
         LEFT JOIN AIMS.INTO_STATION c on b.STATION_ID=c.ID
         LEFT JOIN AIMS.INTO_APPLIANCE d on a.APPLIANCE_ID = d.ID
         LEFT JOIN AIMS.INTO_APPLIANCE_CATEGORY e on d.CATEGORY_ID = e.ID
         LEFT JOIN AIMS.INTO_APPLIANCE_SPEC f on d.SPEC_ID = f.ID

create or replace view AIMS.INTO_WORK_TICKET_VIEW as
select a.ID,a.WORK_TICKET,a.WORK_START_TIME,a.WORK_END_TIME,a.CHARGE_PERSON,a.JOB_CONTENT,a.ORIGINAL_INFO,
       a.WORK_STATUS,a.SECURITY_MEASURES,a.ATTENTION_MATTER,a.SUPPLEMENT,a.FUNCTION_PERSON,a.FUNCTION_DATE,a.CHARGE_ORG_ID,a.WORK_TICKET_STATUS,

       b.NAME ORG_NAME,b.PATH ORG_PATH,b.BMXZNAME org_BMXZNAME,b.com_bmjc org_com_bmjc

from AIMS.INTO_WORK_TICKET a
         LEFT JOIN AIMS.COM_BASEORGNAIZE b on a.CHARGE_ORG_ID=b.OBJ_ID
/

create or replace view AIMS.INTO_WORK_TICKET_MEMBERS_VIEW as
select a.ID,a.WORK_TICKET,a.USER_ID,a.USER_REALNAME,a.USER_TYPE,a.USER_ORG_ID,

       b.NAME ORG_NAME,b.PATH ORG_PATH,b.BMXZNAME org_BMXZNAME,b.com_bmjc org_com_bmjc

from AIMS.INTO_WORK_TICKET_MEMBERS a
         LEFT JOIN AIMS.COM_BASEORGNAIZE b on a.USER_ORG_ID=b.OBJ_ID
/

create or replace view AIMS.INTO_WORK_TICKET_PLACE_VIEW as
select a.ID,a.WORK_TICKET,a.WORK_PLACE,a.VOLTAGE,a.NOTE_NUMBER,a.APPLIANCE_ID,a.INSTALL_TIME,
       a.INSTALL_BY,a.INSTALL_LOOK_BY,a.DISMANTLE_TIME,a.DISMANTLE_BY,a.DISMANTLE_LOOK_BY,
       b.SERIAL_NUM SERIAL_NUM,
       c.name CATEGORY_NAME,
       d.name SPEC_NAME
from AIMS.INTO_WORK_TICKET_PLACE a
         LEFT JOIN AIMS.INTO_APPLIANCE b on a.APPLIANCE_ID=b."ID"
         LEFT JOIN AIMS.INTO_APPLIANCE_CATEGORY c on b.CATEGORY_ID=c.ID
         LEFT JOIN AIMS.INTO_APPLIANCE_SPEC d on b.STATION_ID=b."ID"
/

create or replace view INTO_WORK_TICKET_REQUEST_VIEW as
select a.ID,a.WORK_TICKET,a.STATION_ID,a.CATEGORY_ID,a.VOLTAGE,a.REQUEST_NUM,
       a.COLLECT_NUM,b.NAME STATION_NAME,
       c.name CATEGORY_NAME
from AIMS.INTO_WORK_TICKET_REQUEST a
         LEFT JOIN AIMS.INTO_STATION b on a.STATION_ID=b."ID"
         LEFT JOIN AIMS.INTO_APPLIANCE_CATEGORY c on a.CATEGORY_ID=c.ID
/

create or replace view AIMS.INTO_SCRAP_MAIN_VIEW as
select a.id,a.APPLY_BY,a.APPLY_TIME,a.EXP_CENTER_ID,a.EXP_ORDER,a.SCRAP_STATUS,a.SCRAP_NUMBER,a.SCRAP_TYPE,a.SCRAP_TIME,
       a.REVIEW_BY,a.REVIEW_TIME,a.APPLIANCE_NUM,a.SCRAP_BY,a.SCRAP_EXP_TYPE,a.GROUP_ID,
       a.APPLY_BY_NAME,a.REVIEW_BY_NAME,a.SCRAP_BY_NAME,
       c.EXP_CENTER_NAME EXP_CENTER_NAME,c.EXP_GROUP_ID,
       f.path org_path,f.NAME org_name,
       g.NAME exp_org_name,g.PATH exp_org_path
from AIMS.INTO_SCRAP_MAIN a
         left join AIMS.INTO_EXP_COMPANY_REL c on a.EXP_CENTER_ID=c.ID
         left join AIMS.COM_BASEORGNAIZE g on c.EXP_GROUP_ID=g.OBJ_ID
         left join AIMS.COM_BASEORGNAIZE f on a.GROUP_ID=f.OBJ_ID
/

