spring:
  # 数据源
  datasource:
    url: jdbc:postgresql://10.144.95.192:31336/pms3?searchpath=bd_overallview
    username: power_tf
    password: 1qaz@WSX
    driver-class-name: org.postgresql.Driver
  #    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
applocal:
  uploadfilepath: /Users/chenfeixiang/filespace/fianqijufile
  currentuser:
    currentUserId: 1111
    currentAccount: deZhangguorong
    currentRealName: 福州市账号
    currentOrgId: 8a0f688f46db11f00146db130fa002ce
    currentOrgPath: 国网福建电力/国网福州供电公司/

datacenter:
  businessapi:
    getway: http://dwzyzt.cloudjs.dev.com.cn
    appId:  1122
    appSecret: 2233
    accessToken: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMDAwMDUwOTE5NiIsImlhdCI6MTYyNjE2ODkwNSwic3ViIjoid3doX3BtcyIsImF1ZCI6IuWQtOaWh-m5pCIsImV4cCI6MTYyNjI1NTMwNX0.ZwiTkVXBM952MlBc4HFw0wwNfOj-KBKs_JC9zjPy9CE

# 面向科技 密码
mx:
  sql:
    key: DYPNNKLCB38= # 对称加密钥匙

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: xboot-logs
    # 最大保存天数
    max-history: 7
    # 每个文件最大大小
    max-size: 5MB

